## Assignment
#### Linear Regression
  - Implement Linear Regression using Gradient Descent from scratch on dataset provided in the given folder.
  - You need to predict the performance index of students based on other attributes.
  - You need to implement the model from scratch just using numpy for building the model, you can use any other library for data manipulation and visualization (prepossessing).
  - Use first 90% of the data for training and the remaining 10% for testing.
  - Report RMSE on the test data for model evaluation (you can use any library for this)
  - Your goal is to RSME as low as possible, so try to experiment with all the concepts you have learned till now.
  - Implement the code in .ipynb file and submit it
#### Logistic Regression
  - Implement Logistic Regression using Gradient Descent from scratch on dataset provided in the given folder.
  - You need to predict whether the last column is 1 or 0 based on other attributes.
  - You need to implement the model from scratch just using numpy for building the model, you can use any other library for data manipulation and visualization (prepossessing).
  - Use first 90% of the data for training and the remaining 10% for testing.
  - Report accuracy of your model (percentage of data points classified correctly) along with the confusion matrix.
  - Implement the code in .ipynb file and submit it

In [1]:
import numpy as np
import pandas as pd
import copy

In [2]:
df=pd.read_csv('Student_Performance.csv')

In [3]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({'Yes': 1, 'No': 0})

C:\Users\Shreyas Dey\AppData\Local\Temp\ipykernel_10784\1449698724.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({'Yes': 1, 'No': 0})


In [4]:
df=df.to_numpy()

In [5]:
print(df)

[[ 7 99  1  9  1 91]
 [ 4 82  0  4  2 65]
 [ 8 51  1  7  2 45]
 ...
 [ 6 83  1  8  5 74]
 [ 9 97  1  7  0 95]
 [ 7 74  0  8  1 64]]


In [6]:
train=df[:9000,:]
X_train=train[:,:-1]
y_train=train[:,-1]
test=df[9000:,:]

In [7]:
def compute_gradient(X, y, w, b): 
    m,n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.
    for i in range(m):                             
        err = (np.dot(X[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] = dj_dw[j] + err * X[i, j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                      
    return dj_db, dj_dw

In [8]:
def gradient_descent(X, y, w_in, b_in, gradient_function, alpha, num_iters): 
    w = copy.deepcopy(w_in)
    b = b_in  
    for i in range(num_iters):
        dj_db,dj_dw = gradient_function(X, y, w, b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
    return w, b

In [9]:
w_final, b_final = gradient_descent(X_train, y_train, np.array([0.0,0.0,0.0,0.0,0.0]),0.0, compute_gradient, 
                                                    5.0e-7, 1000)
print(f"b,w found by gradient descent: {b_final},{w_final} ")

b,w found by gradient descent: 0.00950325394901048,[0.05667056 0.73521743 0.00479723 0.06273927 0.04443056] 


In [10]:
def compute_cost(X, y, w, b): 
    m = X.shape[0]
    cost = 0.0
    for i in range(m):                                
        f_wb_i = np.dot(X[i], w) + b           #(n,)(n,) = scalar (see np.dot)
        cost = cost + (f_wb_i - y[i])**2       #scalar
    cost = cost / (2 * m)                      #scalar    
    return cost
X_test=test[:,:-1]
y_test=test[:,-1]
compute_cost(X_test,y_test,w_final,b_final)

np.float64(45.8153880707941)